##############################################################################
#									     #
#   makefile of pds2mngn						     #
#									     #
##############################################################################

# module
NAME = pds2mngn

# libreries
LIB =

# switches
SW = -O -w

# compiler
CC = CC

SOURCE = pds2mngn.C

# main module

$(NAME): $(SOURCE)
	$(CC) $(SOURCE) -o $(NAME) $(LIB) $(SW)

############################ End of makefile #################################
